EnergyStyleCore/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EnergyStyleCore.Models;
using EnergyStyleCore.Models.Classes;
using CustomPolicyProvider;

namespace EnergyStyleCore.Controllers
{
    public class ProductsController : Controller
    {
        private readonly AppDBContext _context;

        public ProductsController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index(int categoryId = 1)
        {
            ViewBag.Categories = await _context.Categories.ToListAsync();
            var products = await _context.Products
                .Include(product => product.Category)
                .Include(product => product.Characteristics)
                .Where(x => x.Category.Id == categoryId)
                .ToListAsync();
            return View(products);
        }

        public async Task<IActionResult> Sales()
        {
            ViewBag.Categories = await _context.Categories.ToListAsync();
            var products = await _context.Products
                .Include(product => product.Category)
                .Include(product => product.Characteristics)
                //.Where(x => x.Sale > 0)
                .ToListAsync();
            return View(nameof(Index), products);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var product = await _context.Products
                .Include(product => product.Category)
                .Include(product => product.Characteristics)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        [RoleAuthorize("user")]
        public async Task<IActionResult> Create()
        {
            ViewBag.Categories = await _context.Categories.ToListAsync();
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [RoleAuthorize("user")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Id,Name,Price,Model,Count,Images,Category,Characteristics")] Product product)//////////////////////////////////////////////////
        {
            if (ModelState.IsValid)
            {
                var category = _context.Categories.Find(product.Category.Id);
                product.Category = category;
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        [RoleAuthorize("user")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var product = await _context.Products
                .Include(product => product.Category)
                .Include(product => product.Characteristics)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            ViewBag.Categories = await _context.Categories.ToListAsync();
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [RoleAuthorize("user")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
            [Bind("Id,Name,Price,Model,Count,Images,Category,Characteristics")] Product product)
        {
            if (id != product.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    var category = _context.Categories.Find(product.Category.Id);
                    product.Category = category;
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        [RoleAuthorize("user")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var product = await _context.Products
                .Include(product => product.Category)
                .Include(product => product.Characteristics)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [RoleAuthorize("user")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

EnergyStyleCore/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EnergyStyleCore.Models;
using EnergyStyleCore.Models.Classes;
using CustomPolicyProvider;

namespace EnergyStyleCore.Controllers
{
    public class ServicesController : Controller
    {
        private readonly AppDBContext _context;

        public ServicesController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Services
        public async Task<IActionResult> Index()
        {
            return View(await _context.Service.ToListAsync());
        }

        // GET: Services/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = await _context.Service
                .FirstOrDefaultAsync(m => m.Id == id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        // GET: Services/Create
        [RoleAuthorize("user")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Services/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [RoleAuthorize("user")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Name,Images,Info")] Service service)
        {
            if (ModelState.IsValid)
            {
                _context.Add(service);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(service);
        }

        // GET: Services/Edit/5
        [RoleAuthorize("user")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = await _context.Service.FindAsync(id);
            if (service == null)
            {
                return NotFound();
            }
            return View(service);
        }

        // POST: Services/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [RoleAuthorize("user")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Name,Images,Info")] Service service)
        {
            if (id != service.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(service);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServiceExists(service.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(service);
        }

        // GET: Services/Delete/5
        [RoleAuthorize("user")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = await _context.Service
                .FirstOrDefaultAsync(m => m.Id == id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        // POST: Services/Delete/5
        [RoleAuthorize("user")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var service = await _context.Service.FindAsync(id);
            _context.Service.Remove(service);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServiceExists(int id)
        {
            return _context.Service.Any(e => e.Id == id);
        }
    }
}

EnergyStyleCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EnergyStyleCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/7713828ed3.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <div class="container">
            <div class="header__top">
                <div class="header__logo">
                    <a href="/"><img src="~/images/logo.png" alt=""></a>
                </div>
                <div class="header__search"><form class="search" action="/"><input type="text" placeholder="Поиск..."><button type="submit"></button></form></div>
                <div id="header__phone" class="header__phone">
                    <a id="call">Заказать звонок</a>
                </div>
                <partial name="_LoginPartial" />
            </div>
            <div class="header__links">
                @Html.ActionLink(" Каталог", "Index", "Products")
                @Html.ActionLink(" Акции", "Sales", "Products")
                @Html.ActionLink(" Наши услуги", "Index", "Services")
                @Html.ActionLink(" О компании", "About", "Home")
                @Html.ActionLink(" Контакты", "Contact", "Home")
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <div class="container">
            <div class="footer__links">
                <div class="footer__link">
                    @Html.ActionLink("Каталог", "Index", "Products")
                    @Html.ActionLink("Акции", "Sales", "Products")
                    @Html.ActionLink("Услуги", "Index", "Services")
                </div>
                <div class="footer__link">
                    @Html.ActionLink("О компании", "About", "Home")
                    @Html.ActionLink("Контакты", "Contact", "Home")
                </div>
                <div id="contacts" class="contacts"></div>
            </div>
            <div class="footer__row">Энергостиль © 2020</div>
        </div>
    </footer>

    <div id="divloading" style="margin: 0px; padding: 0px; position: fixed; right: 0px;
        top: 0px; width: 100%; height: 100%; background-color:#ffffff; z-index: 300001;
        opacity: .8; filter: alpha(opacity=80);display:none">
        <div style="position: absolute; top: 40%; left: 40%; color: black;">
            <img src="~/images/Wedges.gif" />
        </div>
    </div>

    <div class="smodal">
        <div class="smodal-dialog">
            <div class="smodal-header">
                <h3 class="smodal-title">Вопрос к Энергостиль</h3>
                <button id="close" class="smodal-close">&times;</button>
            </div>
            <div class="smodal-body" style="overflow-y:scroll;">
                <!-- вставишь сюда всё что надо -->
                @*<form>
                    <input value="" class="crm-webform-input" type="text" name="DEAL_TITLE" id="DEAL_TITLE" placeholder="Введите Ваше имя">
                </form>*@
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        let $loading = $('#divloading');
        $(document).ajaxStart(() => $loading.show());
        $(document).ajaxStop(() => $loading.hide());

        let call = document.getElementById('call');
        let modal = document.querySelector('.smodal');
        let modalClose = document.querySelector('.smodal-close');

        function toggleModal() {
            modal.classList.toggle('is-open');
        }

        modalClose.addEventListener('click', toggleModal);
        call.addEventListener('click', toggleModal);

        @{var url = Url.Action("GetShopsData", "Home");}
        $.ajax({
            url: '@url',
            type: 'GET',
            contentType: 'application/json',
            success: (data) => {
                console.log(data);
                if (data.length > 0) {
                    let item = data[0];
                    let contacts = $("#contacts");
                    contacts.append(`<p>Наши контакты</p>
                    <a href="tel:${item.localPhone}"><i class="fas fa-phone"></i>${item.localPhone}</a>
                    <a href="mailto:mail@mail.com"><i class="far fa-envelope-open"></i>${item.email}</a>
                    <a href="@Url.Action("Contact", "Home")"><i class="fas fa-search-location"></i>${item.address}</a>`
                    );
                    let header__phone = $("#header__phone");
                    header__phone.append(`<a href="tel:${item.localPhone}"><i class="fas fa-phone"></i>${item.localPhone}</a>`);
                }
            },
            error: (data) => console.error(data),
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>