EnergyStyleCore/Models/Classes/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EnergyStyleCore.Models.Classes
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
    }
}

EnergyStyleCore/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EnergyStyleCore.Models;
using EnergyStyleCore.Models.Classes;
using CustomPolicyProvider;

namespace EnergyStyleCore.Controllers
{
    [RoleAuthorize("user")]
    public class CategoriesController : Controller
    {
        private readonly AppDBContext _context;

        public CategoriesController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Image")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Image")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

EnergyStyleCore/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CustomPolicyProvider;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EnergyStyleCore.Controllers
{
    [RoleAuthorize("user")]
    public class FileController : Controller
    {
        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            if (file != null)
            {
                // await Task.Delay(3000);
                if (file.Length > 0)
                {
                    var fileName = $"user/{Guid.NewGuid()}.jpg";
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\images", fileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(fileStream);
                        return Ok(fileName);
                    }
                }
            }
            return BadRequest();
        }
        [HttpPost]
        public async Task<IActionResult> Uploads(IFormFileCollection files)
        {
            if (files != null)
            {
                var result = new List<string>();
                foreach (var file in files)
                {
                    // await Task.Delay(3000);
                    if (file.Length > 0)
                    {
                        var fileName = $"user/{Guid.NewGuid()}.jpg";
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\images", fileName);
                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await file.CopyToAsync(fileStream);
                            result.Add(fileName);
                        }
                    }
                }
                return Json(result);
            }
            return BadRequest();
        }
    }
}

EnergyStyleCore/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EnergyStyleCore.Models;
using EnergyStyleCore.Models.Classes;
using CustomPolicyProvider;

namespace EnergyStyleCore.Controllers
{
    public class ProductsController : Controller
    {
        private readonly AppDBContext _context;

        public ProductsController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index(int categoryId = 1)
        {
            ViewBag.Categories = await _context.Categories.ToListAsync();
            var products = await _context.Products
                .Include(product => product.Category)
                .Include(product => product.Characteristics)
                .Where(x => x.Category.Id == categoryId)
                .ToListAsync();
            return View(products);
        }

        public async Task<IActionResult> Sales()
        {
            ViewBag.Categories = await _context.Categories.ToListAsync();
            var products = await _context.Products
                .Include(product => product.Category)
                .Include(product => product.Characteristics)
                //.Where(x => x.Sale > 0)
                .ToListAsync();
            return View(nameof(Index), products);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var product = await _context.Products
                .Include(product => product.Category)
                .Include(product => product.Characteristics)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        [RoleAuthorize("user")]
        public async Task<IActionResult> Create()
        {
            ViewBag.Categories = await _context.Categories.ToListAsync();
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [RoleAuthorize("user")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Id,Name,Price,Model,Count,Images,Category,Characteristics")] Product product)//////////////////////////////////////////////////
        {
            if (ModelState.IsValid)
            {
                var category = _context.Categories.Find(product.Category.Id);
                product.Category = category;
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        [RoleAuthorize("user")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var product = await _context.Products
                .Include(product => product.Category)
                .Include(product => product.Characteristics)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            ViewBag.Categories = await _context.Categories.ToListAsync();
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [RoleAuthorize("user")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
            [Bind("Id,Name,Price,Model,Count,Images,Category,Characteristics")] Product product)
        {
            if (id != product.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    var category = _context.Categories.Find(product.Category.Id);
                    product.Category = category;
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        [RoleAuthorize("user")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var product = await _context.Products
                .Include(product => product.Category)
                .Include(product => product.Characteristics)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [RoleAuthorize("user")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

EnergyStyleCore/Views/Categories/Create.cshtml
@model EnergyStyleCore.Models.Classes.Category

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="items__image">
        <div class="slider">
            <div class="btn-infinity-left"></div>
            <div class="infinity-wrap infinity-size">
                <div class="infinity-slider infinity-size">
                    <img id="imgSrc" style="height: auto; width: 470px; display:none" />
                </div>
            </div>
            <div class="btn-infinity-right"></div>
        </div>
    </div>
    <div class="col-md-4">
        <form asp-action="Upload" asp-controller="File" method="post" enctype="multipart/form-data"
              data-ajax="true"
              data-ajax-method="post"
              data-ajax-complete="FileUploaded">
            <div style="display :flex">
                <input type="file" name="file" style="flex-basis:40%" /><br>
                <input type="submit" value="Загрузить" style="flex-basis: 40%" />
            </div>
        </form>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="Image" class="control-label"></label>
                <input id="imgPath" asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="/js/slider.js"></script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EnergyStyleCore/Views/Categories/Delete.cshtml
@model EnergyStyleCore.Models.Classes.Category

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EnergyStyleCore/Views/Categories/Details.cshtml
@model EnergyStyleCore.Models.Classes.Category

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

EnergyStyleCore/Views/Categories/Edit.cshtml
@model EnergyStyleCore.Models.Classes.Category

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="items__image">
        <div class="slider">
            <div class="btn-infinity-left"></div>
            <div class="infinity-wrap infinity-size">
                <div class="infinity-slider infinity-size">
                    <img id="imgSrc" src="@Model.Image" style="height: auto; width: 470px;" />
                </div>
            </div>
            <div class="btn-infinity-right"></div>
        </div>
    </div>
    <div class="col-md-4">
        <form asp-action="Upload" asp-controller="File" method="post" enctype="multipart/form-data"
              data-ajax="true"
              data-ajax-method="post"
              data-ajax-complete="FileUploaded">
            <div style="display :flex">
                <input type="file" name="file" style="flex-basis:40%" /><br>
                <input type="submit" value="Загрузить" style="flex-basis: 40%" />
            </div>
        </form>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="Image" class="control-label"></label>
                <input id="imgPath" asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="/js/slider.js"></script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EnergyStyleCore/Views/Categories/Index.cshtml
@model IEnumerable<EnergyStyleCore.Models.Classes.Category>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="wrapper">
    <div class="category__catalog">
        <div class="content">
            <div class="category__cards">
                @{
                    foreach (var item in Model)
                    {
                        <div class="category__card">
                            <a href="@Url.Action("Index", "Products", new {categoryId =  item.Id})">
                                <img src="@item.Image" alt="">
                                <p>@item.Name</p>
                            </a>
                            <p>
                                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                            </p>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>