EnergyStyleCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using EnergyStyleCore.Models;
using Microsoft.EntityFrameworkCore;
using EnergyStyleCore.Models.Classes;
using CustomPolicyProvider;

namespace EnergyStyleCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDBContext _context;

        public HomeController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetShopsData()
        {
            return Json(_context.Stores.ToList());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [RoleAuthorize("user")]
        public IActionResult Control()
        {
            return View();
        }
    }
}

EnergyStyleCore/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EnergyStyleCore.Models;
using EnergyStyleCore.Models.Classes;
using CustomPolicyProvider;

namespace EnergyStyleCore.Controllers
{
    public class ProductsController : Controller
    {
        private readonly AppDBContext _context;

        public ProductsController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index(int categoryId = 1)
        {
            ViewBag.Categories = await _context.Categories.ToListAsync();
            var products = await _context.Products
                .Include(product => product.Category)
                .Include(product => product.Characteristics)
                .Where(x => x.Category.Id == categoryId)
                .ToListAsync();
            return View(products);
        }

        public async Task<IActionResult> Sales()
        {
            ViewBag.Categories = await _context.Categories.ToListAsync();
            var products = await _context.Products
                .Include(product => product.Category)
                .Include(product => product.Characteristics)
                //.Where(x => x.Sale > 0)
                .ToListAsync();
            return View(nameof(Index), products);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var product = await _context.Products
                .Include(product => product.Category)
                .Include(product => product.Characteristics)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        [RoleAuthorize("user")]
        public async Task<IActionResult> Create()
        {
            ViewBag.Categories = await _context.Categories.ToListAsync();
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [RoleAuthorize("user")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Id,Name,Price,Model,Count,Images,Category,Characteristics")] Product product)//////////////////////////////////////////////////
        {
            if (ModelState.IsValid)
            {
                var category = _context.Categories.Find(product.Category.Id);
                product.Category = category;
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        [RoleAuthorize("user")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var product = await _context.Products
                .Include(product => product.Category)
                .Include(product => product.Characteristics)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            ViewBag.Categories = await _context.Categories.ToListAsync();
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [RoleAuthorize("user")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
            [Bind("Id,Name,Price,Model,Count,Images,Category,Characteristics")] Product product)
        {
            if (id != product.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    var category = _context.Categories.Find(product.Category.Id);
                    product.Category = category;
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        [RoleAuthorize("user")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var product = await _context.Products
                .Include(product => product.Category)
                .Include(product => product.Characteristics)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [RoleAuthorize("user")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

EnergyStyleCore/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EnergyStyleCore.Models;
using EnergyStyleCore.Models.Classes;
using CustomPolicyProvider;

namespace EnergyStyleCore.Controllers
{
    [RoleAuthorize("user")]
    public class StoresController : Controller
    {
        private readonly AppDBContext _context;

        public StoresController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Stores
        public async Task<IActionResult> Index()
        {
            return View(await _context.Stores.ToListAsync());
        }

        // GET: Stores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Stores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (store == null)
            {
                return NotFound();
            }

            return View(store);
        }

        // GET: Stores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Stores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PlaceName,Address,LocalPhone,Email,WorkTime,GeoLong,GeoLat")] Store store)
        {
            if (ModelState.IsValid)
            {
                _context.Add(store);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(store);
        }

        // GET: Stores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Stores.FindAsync(id);
            if (store == null)
            {
                return NotFound();
            }
            return View(store);
        }

        // POST: Stores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PlaceName,Address,LocalPhone,Email,WorkTime,GeoLong,GeoLat")] Store store)
        {
            if (id != store.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(store);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StoreExists(store.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(store);
        }

        // GET: Stores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Stores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (store == null)
            {
                return NotFound();
            }

            return View(store);
        }

        // POST: Stores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var store = await _context.Stores.FindAsync(id);
            _context.Stores.Remove(store);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StoreExists(int id)
        {
            return _context.Stores.Any(e => e.Id == id);
        }
    }
}

EnergyStyleCore/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EnergyStyleCore.Models;
using EnergyStyleCore.Models.Classes;
using CustomPolicyProvider;

namespace EnergyStyleCore.Controllers
{
    [RoleAuthorize("admin")]
    public class UsersController : Controller
    {
        private readonly AppDBContext _context;

        public UsersController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Login == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Login,Password,FirstName,LastName,Role")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Login,Password,FirstName,LastName,Role")] User user)
        {
            if (id != user.Login)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Login))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Login == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(string id)
        {
            return _context.Users.Any(e => e.Login == id);
        }
    }
}

EnergyStyleCore/Views/Home/About.cshtml
<div class="wrapper">
    <div class="about">
        <div class="content">
            <div class="about__company">

                <h1>
                    Компания «Энергостиль» предоставляет комплекс услуг по расчету, комплектации, монтажу систем отопления,
                    горячего и холодного водоснабжения, водоотведения. Производство санитарно-технических работ.
                </h1>

                <h2>БОЛЕЕ 8 ЛЕТ ОПЫТА</h2>

                <p>
                    Наши клиенты – это наши друзья, которым мы всегда готовы помочь в любую минуту.
                    Мы – это дружный и сплоченный коллектив профессионалов, любящих своё дело.
                    Мы всегда предоставляем гарантии на наши работы.
                </p>

                <h2>НАШИ ГАРАНТИИ</h2>

                <h3>Гарантия предоставляется:</h3>
                <ol class="about_li">
                    <li>
                        На безотказную работу систем — 5 лет (без всяких условий).
                    </li>
                    <li>
                        На разъемные соединения 3 года при использовании в системе отопления незамерзающих жидкостей сертифицированных
                        для России и 5 лет для систем отопления на воде и систем водоснабжения.
                    </li>
                    <li>
                        На неразъемные соединения на весь срок службы трубопроводов, заявленный производителем труб и фитингов.
                    </li>
                    <li>
                        На работу оборудования в рамках гарантийных сроков, указанных в паспортах и гарантийных талонах на оборудование.
                        При необходимости ремонта или замены оборудования: если оборудование поставлено подрядчиком —
                        работы производятся бесплатно если оборудование поставлено заказчиком — работы оплачиваются заказчиком.
                    </li>
                    <li>
                        Гарантия на котельное оборудование распространяется только при заключении договора на обслуживание газового или
                        жидкотопливного котла, эксплуатация твердотопливного котла такими условиями не связана и ограничена условиями
                        гарантии производителя.
                    </li>
                </ol>
                <h3>Гарантия не распространяется на случаи:</h3>
                <ol class="about_li">
                    <li>
                        Несанкционированного изменения, ремонта и иного вмешательства третьих лиц в работу смонтированных систем
                    </li>
                    <li>
                        Гарантия не распространяется на случаи эксплуатации систем с нарушением ТУ и СП для материалов из которых выполнена система.
                        То есть, если трубопроводы подверглись деформации, химическому термическому или иному виду воздействия,
                        превышающему допустимые пределы для данного вида материалов.
                    </li>
                </ol>
                <div class="slider">
                    <div class="btn-infinity-left"></div>
                    <div class="infinity-wrap size-about">
                        <div class="infinity-slider size-about">
                            <img src="~/images/certificate/1.BMP" alt="">
                            <img src="~/images/certificate/2.BMP" alt="">
                            <img src="~/images/certificate/3.jpg" alt="">
                            <img src="~/images/certificate/4.jpg" alt="">
                            <img src="~/images/certificate/5.jpg" alt="">
                            <img src="~/images/certificate/6.jpg" alt="">
                            <img src="~/images/certificate/7.jpg" alt="">
                            <img src="~/images/certificate/8.jpg" alt="">
                            <img src="~/images/certificate/9.jpg" alt="">
                            <img src="~/images/certificate/10.jpg" alt="">
                        </div>
                    </div>
                    <div class="btn-infinity-right"></div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/js/slider.js"></script>
}

EnergyStyleCore/Views/Home/Contact.cshtml
@section scripts{
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU"></script>
    <script src="~/js/yamap.js"></script>


    <script>
    @{var url = Url.Action("GetShopsData", "Home");}
    $.ajax({
        url: '@url',
        type: 'GET',
        contentType: 'application/json',
        success: (data) => {
            $.each(data, (i, item) => {
                let div = document.createElement('div');
                div.className = 'commun_left';
                let communication = $('.communication');
                div.innerHTML = `<h3>${item.placeName}</h3>
                <span>Адрес</span>
                <p><i class="fas fa-map-marker-alt"></i>${item.address}</p>
                <span>Телефон</span>
                <a href="tel:${item.localPhone}"><i class="fas fa-phone"></i>${item.localPhone}</a>
                <span>E-mail</span>
                <a href="mailto:mail@mail.com"><i class="far fa-envelope-open"></i>${item.email}</a>
                <span>Режим работы</span>
                <p>${item.workTime}</p>`;
                let parent = document.createElement('div');
                parent.style = "display:flex; flex-direction: row;" +
                    "padding-bottom: 15px; border: 1px solid #ccc;justify-content:space-around;";
                initMap(item, i, parent);
                parent.append(div);
                communication.append(parent);
            });
        },
        error: (data) => { console.log(data); }
    });
    </script>
}
<div class="wrapper">
    <div class="commun">
        <div class="communication">
            <!-- Создаём контейнер для описания -->
            <!--<div id="description" class="commun_left"></div>-->
            <!-- Создаём контейнер для карты -->
            <!--<div class="commun_right" id="map" style="width: 600px; height: 500px"></div>-->

        </div>
    </div>
</div>

EnergyStyleCore/Views/Home/Control.cshtml
@using System.Security.Claims


@if (!string.IsNullOrWhiteSpace(User?.Identity?.Name))
{
    var role = User.FindFirst(c => c.Type == ClaimTypes.Role)?.Value;

    if (role.Contains("admin"))
    {
        <div style="align-self:center; font-size: 20px">
            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index" title="Для настройки">Сотрудники</a>
        </div>
    }
    <div style="align-self:center; font-size: 20px">
        <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index" title="Для настройки">Категории</a>
    </div>
    <div style="align-self:center; font-size: 20px">
        <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index" title="Для настройки">Товары</a>
    </div>
    <div style="align-self:center; font-size: 20px">
        <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Index" title="Для настройки">Услуги</a>
    </div>
    <div style="align-self:center; font-size: 20px">
        <a class="nav-link text-dark" asp-area="" asp-controller="Stores" asp-action="Index" title="Для настройки">Магазины</a>
    </div>
}

EnergyStyleCore/Views/Home/Index.cshtml
@model IEnumerable<EnergyStyleCore.Models.Classes.Category>

<div class="wrapper">
    <div class="category__catalog">
        <div class="content">
            <div class="category__cards">
                @{
                    foreach (var item in Model)
                    {
                        <div class="category__card">
                            <a href="@Url.Action("Index", "Products", new {categoryId =  item.Id})">
                                <img src="@item.Image" alt="">
                                <p>@item.Name</p>
                            </a>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>